// Glossary of the technical terms / abbreviations used across the app. This is
// the WCAG mechanism for 3.1.3 (Unusual Words) and 3.1.4 (Abbreviations):
// a single place where every jargon term and acronym is defined/expanded.
// Term is language-neutral; the definition is translated (same 5 i18n languages).
export type Lang = 'pt-BR' | 'en-US' | 'es' | 'de' | 'fr';
export type GlossaryEntry = { term: string; d: Record<Lang, string> };

const T = (pt: string, en: string, es: string, de: string, fr: string): Record<Lang, string> => ({
  'pt-BR': pt,
  'en-US': en,
  es,
  de,
  fr,
});

export const GLOSSARY: GlossaryEntry[] = [
  { term: 'Hexadecimal (hex)', d: T('Sistema numérico de base 16 (0–9, A–F).', 'Base-16 number system (0–9, A–F).', 'Sistema numérico en base 16 (0–9, A–F).', 'Zahlensystem zur Basis 16 (0–9, A–F).', 'Système numérique en base 16 (0–9, A–F).') },
  { term: 'Binário', d: T('Sistema numérico de base 2 (apenas 0 e 1).', 'Base-2 number system (only 0 and 1).', 'Sistema numérico en base 2 (solo 0 y 1).', 'Zahlensystem zur Basis 2 (nur 0 und 1).', 'Système numérique en base 2 (0 et 1).') },
  { term: 'Octal', d: T('Sistema numérico de base 8 (0–7).', 'Base-8 number system (0–7).', 'Sistema numérico en base 8 (0–7).', 'Zahlensystem zur Basis 8 (0–7).', 'Système numérique en base 8 (0–7).') },
  { term: 'CIDR', d: T('Notação de prefixo de rede (ex.: /24) que indica quantos bits formam a parte de rede do IP.', 'Network-prefix notation (e.g. /24) for how many bits form the network part of an IP.', 'Notación de prefijo de red (p. ej. /24): cuántos bits forman la parte de red de la IP.', 'Netzwerkpräfix-Notation (z. B. /24): wie viele Bits den Netzanteil der IP bilden.', 'Notation de préfixe réseau (p. ex. /24) : combien de bits forment la partie réseau de l’IP.') },
  { term: 'Máscara de sub-rede (netmask)', d: T('Valor (ex.: 255.255.255.0) que separa a parte de rede da parte de host de um IP.', 'Value (e.g. 255.255.255.0) that splits the network part from the host part of an IP.', 'Valor (p. ej. 255.255.255.0) que separa la parte de red de la de host de una IP.', 'Wert (z. B. 255.255.255.0), der Netz- und Host-Teil einer IP trennt.', 'Valeur (p. ex. 255.255.255.0) séparant la partie réseau et la partie hôte d’une IP.') },
  { term: 'Broadcast', d: T('Endereço que envia para todos os hosts de uma sub-rede.', 'Address that sends to every host on a subnet.', 'Dirección que envía a todos los hosts de una subred.', 'Adresse, die an alle Hosts eines Subnetzes sendet.', 'Adresse qui émet vers tous les hôtes d’un sous-réseau.') },
  { term: 'JWT (JSON Web Token)', d: T('Token compacto e assinado (cabeçalho.payload.assinatura) usado para autenticação/autorização.', 'Compact signed token (header.payload.signature) used for authentication/authorization.', 'Token compacto y firmado (cabecera.payload.firma) para autenticación/autorización.', 'Kompaktes signiertes Token (Header.Payload.Signatur) für Authentifizierung/Autorisierung.', 'Jeton compact signé (en-tête.payload.signature) pour l’authentification/autorisation.') },
  { term: 'Base64', d: T('Codificação que representa dados binários como texto ASCII.', 'Encoding that represents binary data as ASCII text.', 'Codificación que representa datos binarios como texto ASCII.', 'Kodierung, die Binärdaten als ASCII-Text darstellt.', 'Encodage représentant des données binaires en texte ASCII.') },
  { term: 'Hash (SHA)', d: T('Função que gera uma “impressão digital” de tamanho fixo de uma entrada (ex.: SHA-256).', 'Function that produces a fixed-size “fingerprint” of an input (e.g. SHA-256).', 'Función que genera una “huella” de tamaño fijo de una entrada (p. ej. SHA-256).', 'Funktion, die einen „Fingerabdruck“ fester Größe einer Eingabe erzeugt (z. B. SHA-256).', 'Fonction produisant une « empreinte » de taille fixe d’une entrée (p. ex. SHA-256).') },
  { term: 'UUID', d: T('Identificador único universal de 128 bits (ex.: versão 4, aleatório).', '128-bit universally unique identifier (e.g. version 4, random).', 'Identificador único universal de 128 bits (p. ej. versión 4, aleatorio).', '128-Bit universell eindeutiger Bezeichner (z. B. Version 4, zufällig).', 'Identifiant unique universel de 128 bits (p. ex. version 4, aléatoire).') },
  { term: 'Timestamp Unix', d: T('Número de segundos desde 1/1/1970 UTC.', 'Number of seconds since 1 Jan 1970 UTC.', 'Número de segundos desde el 1/1/1970 UTC.', 'Anzahl Sekunden seit dem 1.1.1970 UTC.', 'Nombre de secondes depuis le 1/1/1970 UTC.') },
  { term: 'JSON', d: T('Formato de troca de dados baseado em texto (objetos, listas, valores).', 'Text-based data-interchange format (objects, arrays, values).', 'Formato de intercambio de datos basado en texto (objetos, listas, valores).', 'Textbasiertes Datenaustauschformat (Objekte, Arrays, Werte).', 'Format d’échange de données en texte (objets, listes, valeurs).') },
  { term: 'WHOIS', d: T('Protocolo de consulta de dados de registro de domínios e IPs.', 'Protocol to query registration data for domains and IPs.', 'Protocolo para consultar datos de registro de dominios e IPs.', 'Protokoll zur Abfrage von Registrierungsdaten für Domains und IPs.', 'Protocole d’interrogation des données d’enregistrement de domaines et d’IP.') },
  { term: 'Ping (ICMP)', d: T('Testa se um host responde e mede a latência usando pacotes ICMP.', 'Tests whether a host replies and measures latency using ICMP packets.', 'Comprueba si un host responde y mide la latencia con paquetes ICMP.', 'Prüft, ob ein Host antwortet, und misst die Latenz mit ICMP-Paketen.', 'Teste si un hôte répond et mesure la latence via des paquets ICMP.') },
  { term: 'Traceroute', d: T('Mostra os saltos (roteadores) no caminho de rede até um host.', 'Shows the hops (routers) along the network path to a host.', 'Muestra los saltos (routers) en la ruta de red hasta un host.', 'Zeigt die Hops (Router) auf dem Netzwerkpfad zu einem Host.', 'Affiche les sauts (routeurs) sur le chemin réseau vers un hôte.') },
  { term: 'DNS', d: T('Sistema que traduz nomes de domínio em endereços IP.', 'System that translates domain names into IP addresses.', 'Sistema que traduce nombres de dominio en direcciones IP.', 'System, das Domainnamen in IP-Adressen übersetzt.', 'Système qui traduit les noms de domaine en adresses IP.') },
  { term: 'chmod / rwx', d: T('Permissões de arquivo Unix: ler (r=4), gravar (w=2), executar (x=1) por dono/grupo/outros.', 'Unix file permissions: read (r=4), write (w=2), execute (x=1) per owner/group/others.', 'Permisos de archivo Unix: leer (r=4), escribir (w=2), ejecutar (x=1) por propietario/grupo/otros.', 'Unix-Dateirechte: Lesen (r=4), Schreiben (w=2), Ausführen (x=1) je Eigentümer/Gruppe/Andere.', 'Droits de fichier Unix : lire (r=4), écrire (w=2), exécuter (x=1) par propriétaire/groupe/autres.') },
  { term: 'setuid / setgid / sticky', d: T('Bits especiais de permissão: executar como dono/grupo do arquivo; sticky protege arquivos em diretórios compartilhados.', 'Special permission bits: run as the file’s owner/group; sticky protects files in shared directories.', 'Bits de permiso especiales: ejecutar como propietario/grupo del archivo; sticky protege archivos en directorios compartidos.', 'Spezielle Rechte-Bits: als Eigentümer/Gruppe der Datei ausführen; Sticky schützt Dateien in gemeinsamen Verzeichnissen.', 'Bits de permission spéciaux : exécuter en tant que propriétaire/groupe du fichier ; sticky protège les fichiers des répertoires partagés.') },
  { term: 'CPF', d: T('Cadastro de Pessoas Físicas: documento de identificação fiscal de pessoas no Brasil.', 'Brazilian individual taxpayer registry (personal tax ID).', 'Registro fiscal de personas físicas en Brasil (identificación fiscal personal).', 'Brasilianische Steuer-ID für natürliche Personen.', 'Registre fiscal des particuliers au Brésil (identifiant fiscal personnel).') },
  { term: 'CNPJ', d: T('Cadastro Nacional da Pessoa Jurídica: identificação fiscal de empresas no Brasil.', 'Brazilian company taxpayer registry (business tax ID).', 'Registro fiscal de empresas en Brasil (identificación fiscal de empresas).', 'Brasilianische Steuer-ID für Unternehmen.', 'Registre fiscal des entreprises au Brésil (identifiant fiscal d’entreprise).') },
  { term: 'WCAG', d: T('Web Content Accessibility Guidelines: diretrizes de acessibilidade web (níveis A, AA, AAA).', 'Web Content Accessibility Guidelines: web accessibility standards (levels A, AA, AAA).', 'Web Content Accessibility Guidelines: directrices de accesibilidad web (niveles A, AA, AAA).', 'Web Content Accessibility Guidelines: Web-Barrierefreiheitsrichtlinien (Stufen A, AA, AAA).', 'Web Content Accessibility Guidelines : règles d’accessibilité web (niveaux A, AA, AAA).') },
  { term: 'Razão de contraste', d: T('Relação de luminância entre texto e fundo; o AAA exige ≥ 7:1 para texto normal.', 'Luminance ratio between text and background; AAA requires ≥ 7:1 for normal text.', 'Relación de luminancia entre texto y fondo; AAA exige ≥ 7:1 para texto normal.', 'Leuchtdichteverhältnis zwischen Text und Hintergrund; AAA verlangt ≥ 7:1 für normalen Text.', 'Rapport de luminance entre texte et fond ; AAA exige ≥ 7:1 pour le texte normal.') },
  { term: 'Pipe ( | )', d: T('Encadeia comandos enviando a saída de um como entrada do próximo.', 'Chains commands by feeding one command’s output into the next.', 'Encadena comandos enviando la salida de uno como entrada del siguiente.', 'Verkettet Befehle, indem die Ausgabe eines Befehls in den nächsten fließt.', 'Enchaîne des commandes en passant la sortie de l’une à l’entrée de la suivante.') },
  { term: 'tee', d: T('Envia a saída de um comando para a tela E para um arquivo ao mesmo tempo.', 'Sends a command’s output to the screen AND to a file at the same time.', 'Envía la salida de un comando a la pantalla Y a un archivo a la vez.', 'Sendet die Ausgabe eines Befehls gleichzeitig auf den Bildschirm UND in eine Datei.', 'Envoie la sortie d’une commande à l’écran ET dans un fichier en même temps.') },
  { term: 'Libras / VLibras', d: T('Libras: Língua Brasileira de Sinais. VLibras: widget gov.br que traduz texto para Libras com um avatar.', 'Libras: Brazilian Sign Language. VLibras: a gov.br widget that signs text in Libras via an avatar.', 'Libras: lengua de señas brasileña. VLibras: widget de gov.br que traduce texto a Libras con un avatar.', 'Libras: brasilianische Gebärdensprache. VLibras: gov.br-Widget, das Text per Avatar in Libras gebärdet.', 'Libras : langue des signes brésilienne. VLibras : widget gov.br qui traduit le texte en Libras via un avatar.') },
];
